version: '3'

services: 
    jenkins:
        container_name: jenkins
        image: jenkins-ansible
        build: 
            context: jenkins-ansible
        ports: 
            - "9090:8080"
        volumes: 
            - "./jenkins_home:/var/jenkins_home"
        networks: 
            - net
    remote_host:
        container_name: remote_host
        image: remote-host
        build: 
            context: ubuntu
        networks: 
            - net
    db_host:
        container_name: mysql_db
        image: mysql:5.7
        environment: 
            - "MYSQL_ROOT_PASSWORD=password"
        volumes: 
            - "./mysql:/var/lib/mysql"
        networks: 
            - net
    
networks: 
    net: 